from .lofi_creation import (
    NODE_CLASS_MAPPINGS as LCM,
    NODE_DISPLAY_NAME_MAPPINGS as LDNM,
)
from .ximi_string_pass import (
    NODE_CLASS_MAPPINGS as SPCM,
    NODE_DISPLAY_NAME_MAPPINGS as SPDNM,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(LCM)
NODE_CLASS_MAPPINGS.update(SPCM)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(LDNM)
NODE_DISPLAY_NAME_MAPPINGS.update(SPDNM)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
